version: "3.3"
services:
  vehicle-geolocation:
    container_name: vehicle-geolocation
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_FLYWAY_URL=jdbc:mysql://mysql:3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/vehicle-geolocation
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      MYSQL_DATABASE: vehicle-geolocation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
